### PR TITLE
Update high-availability and k8s-sandbox to 1.0.0-rc2

### PR DESCRIPTION
**Pull request by oicheryl**

### CODE REVIEW

**Comment by BenHall** [comment]
@Arau This delay is only because the new image hasn't been rolled out. Do you want me to go ahead and do that?

**Comment by oicheryl** [comment]
@BenHall which new image is this? These are using "storageos-kubernetes" and "storageos-docker-3node".

@Arau I've made the changes requested; will merge.

**Comment by BenHall** [comment]
@oicheryl The image I built yesterday with the images pre-cached

**Comment by oicheryl** [comment]
@BenHall It would be good to have storageos/node:1.0.0-rc2 precached (although we're about to release rc3...) and the storageos/init:0.1 image too.

At some point I also need the CLI updated from 0.10 to 1.0.0-rc1.

**Pull request merged**
